# Controller Manager configuration
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    # Define the available controllers
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    rl_quadruped_controller:
      type: rl_quadruped_controller/RLQuadrupedController



imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "imu_sensor"
    frame_id: "imu_link"

rl_quadruped_controller:
  ros__parameters:
    update_rate: 50  # Hz
    robot_pkg: "bigreddog_description"
    model_folder: "legged_gym"
    policy_path: /home/crazydogv2/test/ros2_ws/src/reddog_ROS2Control/descriptions/bigreddog_description/config/legged_gym/policy_1.pt
    config_path: /home/crazydogv2/test/ros2_ws/src/reddog_ROS2Control/descriptions/bigreddog_description/config/legged_gym/big_reddog_him.yaml
    
    joints:
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint

    command_interfaces:
      - position
      - velocity
      - effort
      - kp
      - kd

    state_interfaces:
      - position
      - velocity
      - effort

    feet_names:
      - FL_foot
      - FR_foot
      - RL_foot
      - RR_foot

    imu_name: "imu_sensor"
    base_name: "base"

    imu_interfaces:
      - orientation.w
      - orientation.x
      - orientation.y
      - orientation.z
      - angular_velocity.x
      - angular_velocity.y
      - angular_velocity.z
      - linear_acceleration.x
      - linear_acceleration.y
      - linear_acceleration.z

