# 
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

kps: 40
kds: 1

default_angles: [ 0.1, 0.4, -1.0, -0.1, 0.4, -1.0, 0.1, -0.4, 1.0, -0.1, -0.4, 1.0]
initial_angles: [ 0.1, 0.4, -1.0, -0.1, 0.4, -1.0, 0.1, -0.4, 1.0, -0.1, -0.4, 1.0]
sit_angles: [0.0, 2.54, -2.7, -0.0, 2.54, -2.7, -0.0, -2.54, 2.7, 0.0, -2.54, 2.7]

lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25 
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 270
one_step_obs_size: 45
obs_buffer_size: 6

cmd_init: [0.0 , 0.0, 0.0]