# 
# Simulation time step
dt: 0.005

steering_kps: 8.0
steering_kds: 0.4

wheel_kps: 0.0
wheel_kds: 1.0

default_angles: [0, 0, 0, 0, 0, 0, 0, 0]
wheelbase: 0.45
trackwidth: 0.23

cmd_scale: 20.0
cmd_init: [0.0, 0.0, 0.0]